# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-08 09:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='comment',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='comment',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='location',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='consus.Location'),
        ),
    ]
